export const DEBUG = process.env.DEBUG === 'true';
export const API_SERVER = process.env.API_URL;

export const DEFAULT_AVATAR = `${API_SERVER}/uploads/avatar.jpg`;
export const DEFAULT_COMPANY_AVATAR = `${API_SERVER}/uploads/company-logo.png`;

export const TOKEN_LOCALSTORAGE_KEY = 'token';

export const ROLES = {
  seeker: 'Seeker',
  employer: 'Employer',
  admin: 'Admin',
};

export const ENGLISH_LEVELS = [
  'No English',
  'Beginner/Elementary',
  'Pre-Intermediate',
  'Intermediate',
  'Upper-Intermediate',
  'Advanced/Fluent',
];

export const CATEGORIES = [
  { value: 'Not Selected', label: 'Not Selected' },
  {
    group: 'DEVELOPMENT',
    items: [
      'JavaScript/Front-End',
      'Fullstack',
      'React Native',
      'Java',
      'C#/.NET',
      'Python',
      'PHP',
      'Node.js',
      'iOS',
      'Android',
      'C/C++/Embedded',
      'Flutter',
      'Goland',
      'Ruby',
      'Scala',
      'Salesforce',
      'Rust',
    ],
  },
  {
    group: 'MORE DEVELOPMENT',
    items: [
      'QA Manual',
      'QA Automation',
      'Design/UI/UX',
      '2D/3D Artist/Illustrator',
      'Project Manager',
      'Product Manager',
      'Architect/CTO',
      'DevOps',
      'Business Analyst',
      'Data Science',
      'Data Analyst',
      'Sysadmin',
      'Gamedev/Unity',
      'SQL/DBA',
      'Security',
      'Data Engineer',
      'Scrum Master/Agile Coach',
    ],
  },
  {
    group: 'NON-TECHNICAL',
    items: [
      'Marketing',
      'HR',
      'Recruiter',
      'Customer/Technical Support',
      'Sales',
      'SEO',
      'Technical Writting',
      'Lead Generation',
      'Head/Chief',
      'Other',
    ],
  },
];

export const EXPERIENCE_YEARS = [
  { value: 0 },
  { value: 0.5 },
  { value: 1 },
  { value: 1.5 },
  { value: 2 },
  { value: 2.5 },
  { value: 3 },
  { value: 3.5 },
  { value: 4 },
  { value: 5 },
  { value: 6 },
  { value: 7 },
  { value: 8 },
  { value: 9 },
  { value: 10 },
];

export const COMPANY_TYPES = [
  'Product',
  'Outsource',
  'Outstaff',
  'Agency',
  'Startup',
];

export const EXPERIENCE_LEVELS = [
  'Trainee',
  'Junior',
  'Middle',
  'Senior',
  'Lead',
  'Chief',
];

export const EMPLOYMENT = ['Remote', 'Office', 'Part-time', 'Freelance'];

export const DEV_DOMAINS = [
  'Web Development',
  'Enterprise Software, ERP, CRM',
  'E-commerce',
  'Modile Development',
  'UX/UI Design',
  'Blockchain/Crypto',
  'DevOps',
];

export const NOT_CONSIDER_DOMAINS = [
  'Adult',
  'Gambling',
  'Dating',
  'Gamedev',
  'Blockchain/Crypto',
];

export const COUNTRIES = [
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands Cocos',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic of The Congo',
  'Cook Islands',
  'Costa Rica',
  "Cote D'ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic of Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea, Democratic People's Republic of Korea",
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States ofMicronesia',
  'Moldova, Republic of Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory, Occupied',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and The Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and The South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of Tanzania',
  'Thailand',
  'Timor-leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const SKILLS = [
  'HTML5',
  'CSS3',
  'Bootstrap',
  'Tailwind CSS',
  'SCSS',
  'SASS',
  'JavaScript',
  'TypeScript',
  'Gulp',
  'Babel.js',
  'Webpack',
  'Vite.js',
  'React',
  'Redux',
  'ReduxtToolkit',
  'Node.js',
  'Express.js',
  'MongoDB',
  'PostgreSQL',
  'Python',
  'Java',
  'PHP',
  'Goolang',
  'C',
  'C#',
  'C++',
  'Amazon Web',
  'Docker',
  'GitHub',
  'GitLab',
  'Next.js',
  'Gatsby.js',
  'Nest.js',
  'Vue',
  'Vuex',
  'Angular',
  'RxJs',
  'MySQL',
  'Laravel',
  'Symfoni',
  'ApolloClient',
  'GraphQL',
  'Socket.io',
  'EsLint',
  'Prettier',
  'MaterialUI',
  'Chakra UI',
  'Ant Design',
  'i18next',
  'Formik',
  'Yup',
  'React Hook Form',
  'Styled Components',
  'Ethers.js',
  'Jest',
  'React testing Library',
  'GitHub Actions',
  'React Query',
  'Swift',
  'Objective-C',
  'Dart',
  'Flutter',
  'React Native',
  'Ionic',
  'Electron',
  'React-Charts',
  'Pug',
  'Ajax',
  'Astro',
  'Mantine',
  'Axios',
  'Husky',
  'Redis',
  'Google Cloud',
  'CI/CD',
  'Firebase',
  'OAuth2',
  'npm',
  'Postman',
  'Swagger',
  'esbuild',
  'StoryBook',
];

export const NOTIFICATION_TYPES = {
  applyToJob: 'application-to-job',
};
